#%RAML 1.0
title: ACHCaseManager
version: v1
baseUri: http://localhost:8080/ACHCaseManager/api/
types:
  TestType:
    type: object
    properties:
      id: number
      optional?: string
      expanded:
        type: object
        properties:
          count: number

/cases:
  description: Respond with ALL cases
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              [{
              "id": 1,
              "openedBy": "Anna Nguyen",
              "updatedBy": "Lisa Hawkins",
              "openedDate": "5/29/2015",
              "sla": "11/13/2015",
              "beneficiaryName": "Gary Ford",
              "status": "opened",
              "notes": ["This case is hard"]
              },
              {
              "id": 2,
              "openedBy": "Joan Wagner",
              "updatedBy": "Chris Murphy",
              "openedDate": "9/9/2015",
              "sla": "12/22/2015",
              "beneficiaryName": "Carl Ray",
              "status": "opened",
              "notes": ["I don't like this project...", "I wish they would stop rapping!"]
              },
              {
              "id": 3,
              "openedBy": "Frances Williamson",
              "updatedBy": "Daniel Hudson",
              "openedDate": "8/7/2015",
              "sla": "10/11/2015",
              "beneficiaryName": "Rose Jordan",
              "status": "assigned",
              "notes": ["This case is almost done!", "Is this case over yet?", "Another note"]
              }
              ]
/users:
  description: Respond with ALL users
  get:
/case/{id}:
  /fields:
    description: Respond with all fields and values for this case
    get:
  /audits:
    description: Respond with all audits of this case
    get:
  /payments:
    description: Respond with all payments for this case
    get:
/user/{id}:
  /cases:
    description: Respond with all cases assigned to this user
    get:
  /audits/{startDate}/{endDate}:
    description: Respond with all audits made by this user within a given date range
    get:
